version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_server
    environment:
      POSTGRES_DB: deanery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass_deanery
    ports:
      - "2345:5432"
    volumes:
      - ./Database/Source/deanery.sql:/docker-entrypoint-initdb.d/deanery.sql
  blazorserver:
    image: blazorserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:80
      - 7443:443
    links:
      - postgres
